steps:
  - name: build-archieve
    when:
      event: [tag, push]
    image: alpine:3
    commands:
      - echo "FIX ME"
      - apk update && apk add libusb-dev make gcc musl-dev argp-standalone
      - make
      - mkdir -p /builds/argbColors
      - cp bin/argbColors /builds/argbColors/
    volumes:
      - /home/www/builds:/builds
